# Generated by Django 3.1.7 on 2021-03-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20201005_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
