# Generated by Django 3.1.7 on 2021-03-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.IntegerField(blank=True),
        ),
    ]
